name: First Interaction

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  first-interaction:
    runs-on: ubuntu-latest
    steps:
      - name: Greet new contributors
        uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: |
            🎉 **Thank you for opening your first Issue with OpenMechanicalAI!** 🎉

            We’re excited to have you on board.

            ✅ Please review:
            - Our [Project Board](https://github.com/YOUR-USERNAME/open-mechanical-ai/projects/1)
            - [Contribution Guidelines](https://github.com/YOUR-USERNAME/open-mechanical-ai/blob/main/CONTRIBUTING.md)

            Feel free to also introduce yourself in the Community thread! 🚀
          
          pr-message: |
            🎉 **Thank you for submitting your first Pull Request to OpenMechanicalAI!** 🎉

            We appreciate your contribution.

            ✅ Please double-check:
            - The [Contribution Guidelines](https://github.com/YOUR-USERNAME/open-mechanical-ai/blob/main/CONTRIBUTING.md)
            - Linked your PR to an Issue if applicable.

            Excited to collaborate with you! 🚀
